version: "3.8"

services:
    postgres:
        image: postgres:14
        ports:
            - "25432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Upbase2022
            - POSTGRES_DB=postgres
        volumes:
            - upbase_oms_cqrs:/var/lib/postgresql/data
        command:
            [
                "postgres",
                "-c",
                "wal_level=logical",
                "-c",
                "max_wal_senders=2",
                "-c",
                "max_replication_slots=2",
                "-c",
                "log_statement=all",
                "-c",
                "logging_collector=on",
                "-c",
                "log_directory=pg_log",
                "-c",
                "log_duration=on",
            ]
    redis:
        image: redis
        command: redis-server
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
        ports:
            - "9211:9200"
            - "9311:9300"
        environment:
            - xpack.security.enabled=false
            - network.host=127.0.0.1
            - http.host=0.0.0.0
    kibana:
        image: docker.elastic.co/kibana/kibana:7.17.13
        ports:
            - "5611:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch
    pgsync:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "chmod +x ./docker/runserver.sh && ./docker/runserver.sh"
        tty: true
        volumes:
            - .:/code
        sysctls:
            - net.ipv4.tcp_keepalive_time=200
            - net.ipv4.tcp_keepalive_intvl=200
            - net.ipv4.tcp_keepalive_probes=5
        labels:
            org.label-schema.name: "pgsync"
            org.label-schema.description: "Postgres to Elasticsearch sync"
            com.label-schema.service-type: "daemon"
        depends_on:
            - postgres
            - redis
            - elasticsearch
        environment:
            - PG_USER=postgres
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_PASSWORD=Upbase2022
            - LOG_LEVEL=DEBUG
            - ELASTICSEARCH_PORT=9200
            - ELASTICSEARCH_SCHEME=http
            - ELASTICSEARCH_HOST=elasticsearch
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_AUTH=
            - ELASTICSEARCH=true
            - CONSOLE_LOGGING_HANDLER_MIN_LEVEL=DEBUG
            - CHECKPOINT_PATH=checkpoint_path
            - ELASTICSEARCH_TIMEOUT=60
            - WAL=true
volumes:
    upbase_oms_cqrs: {}
